included time logger for communication and attention's gemm into analyzer.

diff --git a/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template b/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
--- a/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
+++ b/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
@@ -22,6 +22,14 @@ TRAIN_ITERS={{TRAIN_ITERS}}
 MOE_TYPE="{{MOE_TYPE}}"
 MODEL_SIZE="{{MODEL_SIZE}}"
 
+
+echo "MICRO_BATCH_SIZE: $BATCH_SIZE"
+echo "GLOBAL_BATCH_SIZE: $GLOBAL_BATCH_SIZE"
+echo "PP_SIZE: $PP_SIZE"
+echo "EP_SIZE: $EP_PARALLEL_SIZE"
+echo "NODES: $NODES"
+echo "TOTAL_GPUS: $TOTAL_GPUS"
+
 # --- Conditional Logic ---
 # Set DeepSpeed flags and other settings based on whether this is a PP run.
 if [[ ${PP_SIZE} -gt 1 ]]; then
@@ -54,15 +62,86 @@ DIR=`pwd`
 ###############################################################################
 ### Main configs (These are now common to all runs)
 
-if [[ "${MODEL_SIZE}" == "16B" ]]; then
-    echo "Configuring DeepSeek-V1 16B"
+if [[ "${MODEL_SIZE}" == "10B" ]]; then
+    echo "Configuring DeepSeek-V1 10B"
     NUM_LAYERS=28
-    MODEL_SIZE=16
+    MODEL_SIZE=10
     HIDDEN_SIZE=2048
     FFN_HIDDEN_SIZE=1408
     NUM_ATTN_HEADS=16
     EP_SIZE=64
     topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "10B_div2" ]]; then
+    echo "Configuring ${MODEL_SIZE} Model"
+    NUM_LAYERS=14
+    MODEL_SIZE=5
+    HIDDEN_SIZE=2048
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "10B-4" ]]; then
+    echo "Configuring ${MODEL_SIZE} Model"
+    NUM_LAYERS=24
+    MODEL_SIZE=9
+    HIDDEN_SIZE=2048
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "10B-8" ]]; then
+    echo "Configuring ${MODEL_SIZE} Model"
+    NUM_LAYERS=20
+    MODEL_SIZE=8
+    HIDDEN_SIZE=2048
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "10B-12" ]]; then
+    echo "Configuring ${MODEL_SIZE} Model"
+    NUM_LAYERS=16
+    MODEL_SIZE=6.5
+    HIDDEN_SIZE=2048
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "15B" ]]; then
+    echo "Configuring 15B Model"
+    NUM_LAYERS=28
+    MODEL_SIZE=15
+    HIDDEN_SIZE=3072
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "20B" ]]; then
+    echo "Configuring 20B Model"
+    NUM_LAYERS=28
+    MODEL_SIZE=20
+    HIDDEN_SIZE=4096
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=64
+    topk=6
+    SEQ_LEN=2048
+elif [[ "${MODEL_SIZE}" == "31B" ]]; then
+    echo "Configuring 20B Model"
+    NUM_LAYERS=28
+    MODEL_SIZE=31
+    HIDDEN_SIZE=4096
+    FFN_HIDDEN_SIZE=1408
+    NUM_ATTN_HEADS=16
+    EP_SIZE=96
+    topk=6
+    SEQ_LEN=2048
 else 
     echo "Configuring custom model size"
     NUM_LAYERS=24
@@ -72,12 +151,13 @@ else
     NUM_ATTN_HEADS=16
     EP_SIZE=64
     topk=6
+    SEQ_LEN=2048
 fi 
 
 node=${NODES}
 total_gpu=${TOTAL_GPUS}
 NUM_GPUS=$total_gpu
-SEQ_LEN=2048
+
 
 LR=1.2e-4
 MIN_LR=1.0e-6
@@ -176,6 +256,8 @@ megatron_options=" \
         --using-torchrun \
 	--use-rotary-position-embeddings"
 
+        # --using-torchrun \
+
 # Conditionally append flags based on the MoE type
 if [[ "${MOE_TYPE}" == "X-MOE" ]]; then
     megatron_options="${megatron_options} --use-uneven-all-to-all --use-pft"
@@ -204,6 +286,8 @@ sed "s/CONFIG_BATCH_SIZE/${GLOBAL_BATCH_SIZE}/" ${template_json} \
     | sed "s/WALL_CLOCK_BREAKDOWN/${WALL_CLOCK_BREAKDOWN}/" \
 	  > ${config_json}
 
+# cat ${config_json}
+
 deepspeed_options=" \
 		    --deepspeed \
             --deepspeed_config ${config_json} \
@@ -220,37 +304,37 @@ export CUDA_VISIBLE_DEVICES=$(seq -s, 0 $((NUM_GPUS-1)))
 export NCCL_NET_GDR_LEVEL=3
 export FI_MR_CACHE_MONITOR=userfaultfd
 
-# readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
-# first=${arr[0]}
-# ips=$(ssh "$first" hostname -I)
-# read -ra ip_arr <<< "$ips"
-# export MASTER_ADDR=${ip_arr[0]}
-# echo "MASTER_ADDR=${MASTER_ADDR}"
+readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
+first=${arr[0]}
+ips=$(ssh "$first" hostname -I)
+read -ra ip_arr <<< "$ips"
+export MASTER_ADDR=${ip_arr[0]}
+echo "MASTER_ADDR=${MASTER_ADDR}"
 
 # ======================= FINAL CORRECTED SCRIPT =======================
 
-# 1. Define the Ethernet interface and port.
-export ETHERNET_INTERFACE=eth0
-export MASTER_PORT=29500
+# # 1. Define the Ethernet interface and port.
+# export ETHERNET_INTERFACE=eth0
+# export MASTER_PORT=29500
 
-# 2. Tell the GPU communication library (NCCL) to use this interface.
-export NCCL_SOCKET_IFNAME=${ETHERNET_INTERFACE}
-echo "NCCL will use interface: ${NCCL_SOCKET_IFNAME}"
+# # 2. Tell the GPU communication library (NCCL) to use this interface.
+# export NCCL_SOCKET_IFNAME=${ETHERNET_INTERFACE}
+# echo "NCCL will use interface: ${NCCL_SOCKET_IFNAME}"
 
-# 3. Find the master node's IP address on that specific interface.
-readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
-first_node=${arr[0]}
-master_ip=$(ssh $first_node "ip -4 addr show ${ETHERNET_INTERFACE} | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
+# # 3. Find the master node's IP address on that specific interface.
+# readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
+# first_node=${arr[0]}
+# master_ip=$(ssh $first_node "ip -4 addr show ${ETHERNET_INTERFACE} | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
 
-if [[ -z "${master_ip}" ]]; then
-    echo "ERROR: Could not determine MASTER_ADDR for ${ETHERNET_INTERFACE} on master node ${first_node}."
-    exit 1
-fi
+# if [[ -z "${master_ip}" ]]; then
+#     echo "ERROR: Could not determine MASTER_ADDR for ${ETHERNET_INTERFACE} on master node ${first_node}."
+#     exit 1
+# fi
 
-# 4. Export the clean MASTER_ADDR and MASTER_PORT.
-export MASTER_ADDR=$master_ip
-echo "MASTER_ADDR has been set to the Ethernet IP: ${MASTER_ADDR}"
-echo "MASTER_PORT has been set to: ${MASTER_PORT}"
+# # 4. Export the clean MASTER_ADDR and MASTER_PORT.
+# export MASTER_ADDR=$master_ip
+# echo "MASTER_ADDR has been set to the Ethernet IP: ${MASTER_ADDR}"
+# echo "MASTER_PORT has been set to: ${MASTER_PORT}"
 
 # ============================ END OF CONFIGURATION ============================
 
@@ -263,15 +347,26 @@ echo "MASTER_PORT has been set to: ${MASTER_PORT}"
 export TRITON_DISABLE_CACHE=1
 export to_profile="False"
 # export to_profile="True"
-export profile_memory="False"
-# export profile_memory="True"
+# export profile_memory="False"
+export profile_memory="True"
 export profile_dir="../scripts/torch_profile/${current_time}/"
 
+# srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
+#     bash -c "export OMPI_MCA_pml=ob1; \
+#             export OMPI_MCA_btl=self,tcp; \
+#             export OMPI_MCA_btl_tcp_if_include=${ETHERNET_INTERFACE}; \
+#             export RANK=\$SLURM_PROCID; \
+#              export WORLD_SIZE=\$SLURM_NTASKS; \
+#              export LOCAL_RANK=\$SLURM_LOCALID; \
+#              python ../pretrain_gpt_deepspeed.py \
+#              ${megatron_options} \
+#              ${data_options} \
+#              ${deepspeed_options} \
+#              --master-addr=$MASTER_ADDR \
+#              --zero-stage 1 \
+#              2>&1 | tee n${total_gpu}-Small-XMoE-${RUN_TYPE}.log"
 srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
-    bash -c "export OMPI_MCA_pml=ob1; \
-            export OMPI_MCA_btl=self,tcp; \
-            export OMPI_MCA_btl_tcp_if_include=${ETHERNET_INTERFACE}; \
-            export RANK=\$SLURM_PROCID; \
+    bash -c "export RANK=\$SLURM_PROCID; \
              export WORLD_SIZE=\$SLURM_NTASKS; \
              export LOCAL_RANK=\$SLURM_LOCALID; \
              python ../pretrain_gpt_deepspeed.py \
@@ -293,7 +388,7 @@ python  /work1/mzhang/zixianw4/X-MoE/Megatron-DeepSpeed-X-MoE/examples_xmoe/scri
         --iterations $TRAIN_ITERS \
         --nodes $node \
         --gpus_per_node $gpus_per_node \
-        --megatron_pp $PP_SIZE \
+        --pp $PP_SIZE \
         --ep $EP_PARALLEL_SIZE \
         --dp $(( total_gpu / PP_SIZE / MP_SIZE )) \
         --tp $MP_SIZE \
@@ -306,4 +401,5 @@ python  /work1/mzhang/zixianw4/X-MoE/Megatron-DeepSpeed-X-MoE/examples_xmoe/scri
         --expert_dim $FFN_HIDDEN_SIZE \
         --topk $topk \
         --hidden_dim $HIDDEN_SIZE \
-        --moe_type $MOE_TYPE 
+        --moe_type $MOE_TYPE \
+        --model_size $MODEL_SIZE
