update multinode run template for hpcfund. Update analyzer to have unspecified folder dir

diff --git a/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template b/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
--- a/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
+++ b/examples_xmoe/scripts-hpcfund/xmoe_unified.slurm.template
@@ -2,7 +2,7 @@
 
 #SBATCH -J {{MOE_TYPE}}-{{RUN_TYPE}}-gbs{{GLOBAL_BATCH_SIZE}}
 #SBATCH -o /work1/mzhang/zixianw4/xmoe-{{RUN_TYPE}}-%j.o
-#SBATCH -t 2:00:00
+#SBATCH -t 1:00:00
 #SBATCH -p batch
 #SBATCH -N {{NODES}}
 #SBATCH -n {{TOTAL_GPUS}}
@@ -304,40 +304,6 @@ export CUDA_VISIBLE_DEVICES=$(seq -s, 0 $((NUM_GPUS-1)))
 export NCCL_NET_GDR_LEVEL=3
 export FI_MR_CACHE_MONITOR=userfaultfd
 
-readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
-first=${arr[0]}
-ips=$(ssh "$first" hostname -I)
-read -ra ip_arr <<< "$ips"
-export MASTER_ADDR=${ip_arr[0]}
-echo "MASTER_ADDR=${MASTER_ADDR}"
-
-# ======================= FINAL CORRECTED SCRIPT =======================
-
-# # 1. Define the Ethernet interface and port.
-# export ETHERNET_INTERFACE=eth0
-# export MASTER_PORT=29500
-
-# # 2. Tell the GPU communication library (NCCL) to use this interface.
-# export NCCL_SOCKET_IFNAME=${ETHERNET_INTERFACE}
-# echo "NCCL will use interface: ${NCCL_SOCKET_IFNAME}"
-
-# # 3. Find the master node's IP address on that specific interface.
-# readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
-# first_node=${arr[0]}
-# master_ip=$(ssh $first_node "ip -4 addr show ${ETHERNET_INTERFACE} | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
-
-# if [[ -z "${master_ip}" ]]; then
-#     echo "ERROR: Could not determine MASTER_ADDR for ${ETHERNET_INTERFACE} on master node ${first_node}."
-#     exit 1
-# fi
-
-# # 4. Export the clean MASTER_ADDR and MASTER_PORT.
-# export MASTER_ADDR=$master_ip
-# echo "MASTER_ADDR has been set to the Ethernet IP: ${MASTER_ADDR}"
-# echo "MASTER_PORT has been set to: ${MASTER_PORT}"
-
-# ============================ END OF CONFIGURATION ============================
-
 
 
 # export NCCL_DEBUG=INFO
@@ -351,21 +317,110 @@ export to_profile="False"
 export profile_memory="True"
 export profile_dir="../scripts/torch_profile/${current_time}/"
 
-# srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
-#     bash -c "export OMPI_MCA_pml=ob1; \
-#             export OMPI_MCA_btl=self,tcp; \
-#             export OMPI_MCA_btl_tcp_if_include=${ETHERNET_INTERFACE}; \
-#             export RANK=\$SLURM_PROCID; \
-#              export WORLD_SIZE=\$SLURM_NTASKS; \
-#              export LOCAL_RANK=\$SLURM_LOCALID; \
-#              python ../pretrain_gpt_deepspeed.py \
-#              ${megatron_options} \
-#              ${data_options} \
-#              ${deepspeed_options} \
-#              --master-addr=$MASTER_ADDR \
-#              --zero-stage 1 \
-#              2>&1 | tee n${total_gpu}-Small-XMoE-${RUN_TYPE}.log"
-srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
+
+
+
+
+if [[ $node -gt 1 ]]; then 
+
+    # ======================= FINAL CORRECTED SCRIPT =======================
+    # export ETHERNET_INTERFACE=eth0
+    # export IB_INTERFACE=ib0
+    # export MASTER_PORT=29500
+
+    # # 2. Tell the GPU communication library (NCCL) to use this interface.
+    # export NCCL_SOCKET_IFNAME=${ETHERNET_INTERFACE}
+    # echo "NCCL will use interface: ${NCCL_SOCKET_IFNAME}"
+
+    # # 3. Find the master node's IP address on that specific interface.
+    # readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
+    # first_node=${arr[0]}
+    # # This command is now more specific to get the IP of the chosen interface.
+    # master_ip=$(ssh $first_node "ip -4 addr show ${ETHERNET_INTERFACE} | grep 'inet' | awk '{print \$2}' | cut -d/ -f1")
+
+
+    # if [[ -z "${master_ip}" ]]; then
+    #     echo "ERROR: Could not determine MASTER_ADDR for ${ETHERNET_INTERFACE} on master node ${first_node}."
+    #     exit 1
+    # fi
+
+    # # 4. Export the clean MASTER_ADDR and MASTER_PORT.
+    # export MASTER_ADDR=$master_ip
+    # echo "nodes>1: MASTER_ADDR=${MASTER_ADDR}"
+    # echo "first_node: ${first_node}"
+    # echo "master_ip: ${master_ip}"
+    # # echo "MASTER_ADDR has been set to the Ethernet IP: ${MASTER_ADDR}"
+    # # echo "MASTER_PORT has been set to: ${MASTER_PORT}"
+
+
+    # srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
+    # bash -c "export OMPI_MCA_pml=ob1; \
+    #         export OMPI_MCA_btl=self,tcp; \
+    #         export OMPI_MCA_btl_tcp_if_include=${ETHERNET_INTERFACE}; \
+    #         export RANK=\$SLURM_PROCID; \
+    #          export WORLD_SIZE=\$SLURM_NTASKS; \
+    #          export LOCAL_RANK=\$SLURM_LOCALID; \
+    #          python ../pretrain_gpt_deepspeed.py \
+    #          ${megatron_options} \
+    #          ${data_options} \
+    #          ${deepspeed_options} \
+    #          --master-addr=$MASTER_ADDR \
+    #          --zero-stage 1 \
+    #          2>&1 | tee n${total_gpu}-Small-XMoE-${RUN_TYPE}.log"
+        # 1. Define the subnet for the high-speed InfiniBand network.
+    #    This is more reliable than a hardcoded interface name.
+    IB_SUBNET="10.0.200."
+    export MASTER_PORT=29500
+
+    # 2. Find the master node's InfiniBand interface and IP address programmatically.
+    readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
+    first_node=${arr[0]}
+
+    # This command finds the interface name and IP on the master node that matches the IB_SUBNET
+    # It's a bit complex, but very reliable.
+    ib_info=$(ssh $first_node "ip -4 a | grep 'inet ${IB_SUBNET}'")
+    if [[ -z "${ib_info}" ]]; then
+        echo "ERROR: Could not find an interface on the IB_SUBNET (${IB_SUBNET}) on master node ${first_node}."
+        exit 1
+    fi
+    master_ip=$(echo $ib_info | awk '{print $2}' | cut -d/ -f1)
+    ib_interface=$(echo $ib_info | awk '{print $NF}') # $NF gets the last field, which is the interface name
+
+    # 3. Export the discovered values for the training job.
+    export MASTER_ADDR=$master_ip
+    export NCCL_SOCKET_IFNAME=${ib_interface}
+
+    echo "Discovered InfiniBand Interface: ${ib_interface}"
+    echo "NCCL will use interface: ${NCCL_SOCKET_IFNAME}"
+    echo "nodes>1: MASTER_ADDR=${MASTER_ADDR}"
+    echo "first_node: ${first_node}"
+
+
+    srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
+    bash -c "export OMPI_MCA_pml=ob1; \
+            export OMPI_MCA_btl=self,tcp; \
+            export OMPI_MCA_btl_tcp_if_include=${NCCL_SOCKET_IFNAME}; \
+            export RANK=\$SLURM_PROCID; \
+            export WORLD_SIZE=\$SLURM_NTASKS; \
+            export LOCAL_RANK=\$SLURM_LOCALID; \
+            python ../pretrain_gpt_deepspeed.py \
+            ${megatron_options} \
+            ${data_options} \
+            ${deepspeed_options} \
+            --master-addr=$MASTER_ADDR \
+            --zero-stage 1 \
+            2>&1 | tee n${total_gpu}-Small-XMoE-${RUN_TYPE}.log"
+
+    # ============================ END OF CONFIGURATION ============================
+else
+    readarray -t arr < <(scontrol show hostnames $SLURM_NODELIST)
+    first=${arr[0]}
+    ips=$(ssh "$first" hostname -I)
+    read -ra ip_arr <<< "$ips"
+    export MASTER_ADDR=${ip_arr[0]}
+    echo "nodes==1: MASTER_ADDR=${MASTER_ADDR}"
+
+    srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
     bash -c "export RANK=\$SLURM_PROCID; \
              export WORLD_SIZE=\$SLURM_NTASKS; \
              export LOCAL_RANK=\$SLURM_LOCALID; \
@@ -376,8 +431,7 @@ srun -N $node -n $total_gpu -c 2 --gpu-bind=closest \
              --master-addr=$MASTER_ADDR \
              --zero-stage 1 \
              2>&1 | tee n${total_gpu}-Small-XMoE-${RUN_TYPE}.log"
-
-
+fi 
 
 
 # --- Analysis Script ---
